### PR TITLE
Implement check for pods that should have sidecar in Proxy Reset

### PR DESCRIPTION
**Pull request by cnvergence**
### Description ###
- Add support for resetting pods without sidecar in the post action.

### See also ###
- https://github.com/kyma-incubator/reconciler/issues/1138

### CODE REVIEW

**Review by tobiscr — APPROVED** [review]

**Review by werdes72 — APPROVED** [review]
/woof

**Review by barchw — APPROVED** [review]

**Review by dariusztutaj — APPROVED** [review]
/meow

**Pull request merged**
