### PR TITLE
Add migration logic for transition from old to new reconciler

### PR DESCRIPTION
**Pull request by tobiscr**
The old reconciler is checking whether a component has a module-CRD on the target cluster. If this is the case, the component is expected to be managed by the new reconciler and the old reconciler will exclude it from the reconciliation.

### CODE REVIEW

**Comment by tobiscr** [comment]
PR blocked by  https://github.com/kyma-project/kyma/issues/17030

**Review by janmedrek — APPROVED** [review]

**Review by jeremyharisch — APPROVED** [review]

**Pull request merged**
