### PR TITLE
Enable windows delivery through build-windows

### LINKED ISSUE #888: Windows Build Target to enable Developerbase on more Architectures
**Description**

Enhance the `Makefile` with a new target for building 2 .exe files for windows, one for mothership and one for reconciler

**Reasons**

This allows developers on Win to build the binaries natively and allows for more flexibility during tests of the isolated binary. The other builds should still be used for our regular targets.

**Attachments**

### PR DESCRIPTION
**Pull request by jakobmoellersap**
Another build target for people who want to run the reconciler binaries native on windows

fixes #888

### CODE REVIEW

**Comment by jakobmoellersap** [comment]
fixes #888

**Comment by jakobmoellersap** [comment]
@jeremyharisch could you tell me whats wrong in the guard job? can't seem to see what's going on.

**Review by jeremyharisch — APPROVED** [review]

**Pull request merged**
