### PR TITLE
Remove PodPreset related code

### PR DESCRIPTION
**Pull request by wozniakjan**
There is a custom reconciler for `cluster-essentials` specifically for handling of `PodPresets`. Pod presets are going to be [removed from kyma entirely](https://github.com/kyma-project/kyma/pull/16647) and have been [deprecated since October 2022](https://kyma-project.io/blog/2022/6/30/release-notes-24#pod-preset-deprecation-note). See also https://github.com/kyma-project/kyma/issues/16656.

I would like to propose removing the `cluster-essentials` reconciler (which should mean default helm reconciler will be used iirc, but that should be fine because now it's the `cluster-essentials` becomes trivial helm chart). This should also allow `pre-main-kyma-gardener-azure-alpha-eval` job passing on https://github.com/kyma-project/kyma/pull/16647.

### CODE REVIEW

**Comment by wozniakjan** [comment]
/hold
pending feedback on https://github.com/kyma-project/kyma/pull/16647#issuecomment-1403515560

**Comment by Tomasz-Smelcerz-SAP** [comment]
I think it's safe to be merged. But I'd like the author, @kwiatekus to confirm - just to be sure.

**Comment by wozniakjan** [comment]
/unhold
green light from @PK85

**Review by jeremyharisch — APPROVED** [review]

**Pull request merged**
